apiVersion: kuma.io/v1alpha1
kind: RateLimit
mesh: default
metadata:
  name: demo-app-redis-rate-limit
spec:
  sources:
    - match:
        kuma.io/service: 'demo-app_kuma-demo_svc_5000'
  destinations:
    - match:
        kuma.io/service: 'redis_kuma-demo_svc_6379'
  conf:
    http:
      requests: 5
      interval: '10s'
      onRateLimit:
        status: 429
        headers:
          - key: "x-kuma-rate-limited"
            value: "true"
            append: true