apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: demo-app-redis-traffic-route
spec:
  sources:
    - match:
        kuma.io/service: demo-app_kuma-demo_svc_5000
  destinations:
    - match:
        kuma.io/service: redis_kuma-demo_svc_6379
  conf:
    split:
      - weight: 50
        destination:
          kuma.io/service: redis_kuma-demo_svc_6379
          version: 'v1'
      - weight: 50
        destination:
          kuma.io/service: redis_kuma-demo_svc_6379
          version: 'v2'